import React, { useState } from 'react';
import { X, Gamepad2 } from 'lucide-react';

export default function AuthModal({ onClose, onSuccess, request }) {
  const [mode,setMode]=useState('login'); const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async(e)=>{e.preventDefault();setError('');setBusy(true);try{await onSuccess(mode,form);}catch(err){setError(err.message);}finally{setBusy(false);}};
  return <div className="scrim" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="auth-modal"><button className="icon-button modal-close" onClick={onClose}><X size={19}/></button><div className="auth-mark"><Gamepad2/><span>NEXUS</span></div><p className="eyebrow">{request==='checkout'?'LISTO PARA TU SIGUIENTE PARTIDA':'ACCESO NEXUS'}</p><h2>{mode==='login'?'Qué bueno verte.':'Crea tu cuenta.'}</h2><p className="muted">{mode==='login'?'Entra para guardar tu setup y revisar tus pedidos.':'Únete y arma un setup a tu medida.'}</p>
    <form onSubmit={submit} className="auth-form">{mode==='register'&&<label>Nombre<input required minLength="2" autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>Correo electrónico<input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Contraseña<input required type="password" minLength="8" autoComplete={mode==='login'?'current-password':'new-password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{mode==='register'&&<small className="muted">Mínimo 8 caracteres, mayúscula, minúscula y número.</small>}{error&&<p className="form-error">{error}</p>}<button className="button button-primary wide" disabled={busy}>{busy?'Un momento…':mode==='login'?'Iniciar sesión':'Crear cuenta'}</button></form>
    <p className="auth-switch">{mode==='login'?'¿Primera vez en NEXUS?':'¿Ya tienes cuenta?'} <button onClick={()=>{setMode(mode==='login'?'register':'login');setError('');}}>{mode==='login'?'Crear cuenta':'Iniciar sesión'}</button></p></section></div>;
}
