import React, { useEffect, useMemo, useState } from 'react';
import { api, money } from './services/api.js';
import AuthModal from './modules/auth/AuthModal.jsx';
import ProductCard from './modules/catalog/ProductCard.jsx';
import OrderList from './modules/orders/OrderList.jsx';
import { ArrowDown, ArrowRight, Check, ChevronDown, Cpu, Gamepad2, Menu, Minus, Monitor, Plus, Search, ShieldCheck, ShoppingBag, ShoppingCart, SlidersHorizontal, Sparkles, UserRound, X } from 'lucide-react';

const heroImage='https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1800&q=90';
const categories=['Todo el setup','PC armada','Monitores','Accesorios'];

export default function App(){
  const [products,setProducts]=useState([]); const [catalogError,setCatalogError]=useState(''); const [category,setCategory]=useState('Todo el setup'); const [query,setQuery]=useState(''); const [cart,setCart]=useState([]); const [favorites,setFavorites]=useState([]); const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('nexus-user'));}catch{return null;}}); const [token,setToken]=useState(()=>localStorage.getItem('nexus-token')); const [modal,setModal]=useState(false); const [drawer,setDrawer]=useState(false); const [notice,setNotice]=useState(''); const [orders,setOrders]=useState([]); const [adminForm,setAdminForm]=useState(false); const [editingProductId,setEditingProductId]=useState(null); const [mobileNav,setMobileNav]=useState(false); const [productDraft,setProductDraft]=useState({name:'',category:'PC armada',description:'',price_mxn:'',stock:'',image_url:'',source_url:''});
  const loadProducts=()=>api('/products').then(items=>{setProducts(items);setCatalogError('');}).catch(()=>{setProducts([]);setCatalogError('No pudimos conectar con el catálogo. Revisa que la API esté iniciada e inténtalo de nuevo.');});
  useEffect(()=>{loadProducts();},[]);
  useEffect(()=>{if(token)api('/orders',{token}).then(setOrders).catch(()=>{});else setOrders([]);},[token]);
  const shown=useMemo(()=>products.filter(p=>(category==='Todo el setup'||p.category===category)&&`${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase())),[products,category,query]);
  const count=cart.reduce((sum,item)=>sum+item.quantity,0); const total=cart.reduce((sum,item)=>sum+Number(item.price_mxn)*item.quantity,0);
  const toast=(text)=>{setNotice(text);setTimeout(()=>setNotice(''),3200);};
  const add=(product)=>{setCart(current=>{const exists=current.find(p=>p.id===product.id);if(exists)return current.map(p=>p.id===product.id?{...p,quantity:Math.min(p.quantity+1,Number(p.stock))}:p);return [...current,{...product,quantity:1}];});toast('Agregado a tu carrito.');};
  const adjust=(id,delta)=>setCart(current=>current.map(item=>item.id===id?{...item,quantity:Math.min(Number(item.stock),Math.max(0,item.quantity+delta))}:item).filter(item=>item.quantity));
  const authenticate=async(mode,form)=>{const data=await api(`/auth/${mode==='register'?'register':'login'}`,{method:'POST',body:JSON.stringify(form)});setToken(data.token);setUser(data.user);localStorage.setItem('nexus-token',data.token);localStorage.setItem('nexus-user',JSON.stringify(data.user));setModal(false);toast(`Qué gusto, ${data.user.name.split(' ')[0]}.`);};
  const checkout=async()=>{if(!token){setModal(true);return;}try{const order=await api('/orders',{method:'POST',token,body:JSON.stringify({items:cart.map(p=>({productId:p.id,quantity:p.quantity}))})});setCart([]);setOrders(await api('/orders',{token}));await loadProducts();toast(`Pedido #${order.id} creado correctamente.`);}catch(e){toast(e.message);}};
  const saveProduct=async(e)=>{e.preventDefault();try{const payload=JSON.stringify({...productDraft,price_mxn:Number(productDraft.price_mxn),stock:Number(productDraft.stock)});await api(editingProductId?`/products/${editingProductId}`:'/products',{method:editingProductId?'PUT':'POST',token,body:payload});setAdminForm(false);setEditingProductId(null);setProductDraft({name:'',category:'PC armada',description:'',price_mxn:'',stock:'',image_url:'',source_url:''});await loadProducts();toast(editingProductId?'Cambios del producto guardados.':'Producto agregado al catálogo.');}catch(e){toast(e.message);}};
  const editProduct=(product)=>{setProductDraft({name:product.name,category:product.category,description:product.description,price_mxn:String(product.price_mxn),stock:String(product.stock),image_url:product.image_url,source_url:product.source_url||''});setEditingProductId(product.id);setAdminForm(true);document.getElementById('account')?.scrollIntoView({behavior:'smooth'});};
  const deleteProduct=async(id)=>{if(!window.confirm('¿Eliminar este producto del catálogo? Si está ligado a un pedido, el sistema lo conservará.'))return;try{await api(`/products/${id}`,{method:'DELETE',token});await loadProducts();toast('Producto eliminado del catálogo.');}catch(e){toast(e.message);}};
  const updateOrder=async(id,status)=>{try{await api(`/orders/${id}`,{method:'PUT',token,body:JSON.stringify({status})});setOrders(await api('/orders',{token}));toast('Estado del pedido actualizado.');}catch(e){toast(e.message);}};
  const logout=()=>{setToken(null);setUser(null);localStorage.removeItem('nexus-token');localStorage.removeItem('nexus-user');};
  return <div className="app-shell">
    <div className="announcement"><Sparkles size={13}/> LEVEL UP YOUR SETUP <span>•</span> Hardware gamer seleccionado · precios de referencia en MXN</div>
    <header className="site-header"><a href="#top" className="brand"><span className="brand-icon"><Gamepad2 size={22}/></span><span>NEXUS<small>PC GAMING</small></span></a><nav className="main-nav"><a className="active" href="#catalogo">Tienda</a><a href="#catalogo" onClick={()=>setCategory('PC armada')}>PC Gamer</a><a href="#catalogo" onClick={()=>setCategory('Monitores')}>Monitores</a><a href="#beneficios">Por qué NEXUS</a></nav><div className="header-actions"><label className="search-box"><Search size={17}/><input placeholder="Busca tu próximo upgrade" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="icon-button account-button" onClick={()=>user?document.getElementById('account')?.scrollIntoView({behavior:'smooth'}):setModal(true)} aria-label="Cuenta"><UserRound size={19}/></button>{user&&<button className="logout-button" onClick={logout}>Salir</button>}<button className="cart-button" onClick={()=>setDrawer(true)}><ShoppingBag size={18}/><span>Carrito</span><b>{count}</b></button></div><button className="mobile-menu icon-button" onClick={()=>setMobileNav(!mobileNav)} aria-label="Abrir menú"><Menu/></button></header>{mobileNav&&<nav className="mobile-nav"><a href="#catalogo" onClick={()=>setMobileNav(false)}>Tienda</a><a href="#catalogo" onClick={()=>{setCategory('PC armada');setMobileNav(false);}}>PC Gamer</a><a href="#catalogo" onClick={()=>{setCategory('Monitores');setMobileNav(false);}}>Monitores</a><a href="#beneficios" onClick={()=>setMobileNav(false)}>Por qué NEXUS</a><button onClick={()=>{setMobileNav(false);setModal(true);}}>Mi cuenta</button></nav>}
    <main id="top"><section className="hero"><img className="hero-photo" src={heroImage} alt="Setup de PC gaming con iluminación"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow"><span/> HARDWARE PARA QUIENES JUEGAN EN SERIO</p><h1>JUEGA A<br/>OTRO <em>NIVEL.</em></h1><p className="hero-description">Tu próxima ventaja empieza con el equipo correcto. Potencia seleccionada, precios claros y cero vueltas.</p><div className="hero-actions"><a className="button button-primary" href="#catalogo">Explorar equipo <ArrowRight size={17}/></a><a className="text-link" href="#featured">Descubre la colección <ArrowDown size={15}/></a></div><div className="hero-proof"><div className="avatar-stack"><i>G</i><i>R</i><i>XP</i></div><span>Hardware elegido para<br/><b>gamers como tú.</b></span><div className="proof-divider"/><span className="proof-stars">PRECIOS<small>con referencia</small></span></div></div><div className="hero-side-note">BUILT FOR THE NEXT LEVEL <span>01 — 04</span></div><div className="hero-scroll">SCROLL PARA EXPLORAR <ArrowDown size={13}/></div></section>
    <section className="trust-strip" id="beneficios"><div><Sparkles/><span><b>Precios transparentes</b><small>Fecha y enlace de consulta</small></span></div><div><ShieldCheck/><span><b>Acceso protegido</b><small>Contraseñas con hash seguro</small></span></div><div><Cpu/><span><b>Hardware seleccionado</b><small>Especificaciones visibles</small></span></div><div><Monitor/><span><b>Seguimiento de pedidos</b><small>Inventario actualizado</small></span></div></section>
    <section className="catalog section-wrap" id="catalogo"><div className="section-heading"><div><p className="eyebrow">SELECCIÓN NEXUS <span className="line"/></p><h2>EL SIGUIENTE UPGRADE<br/><em>TE ESTÁ ESPERANDO.</em></h2></div><div className="catalog-aside"><p>Potencia pensada para dominar la partida. Encuentra el equipo que va contigo.</p><button className="filter-button" onClick={()=>document.querySelector('.category-row')?.scrollIntoView({behavior:'smooth',block:'center'})}><SlidersHorizontal size={15}/> Filtros <ChevronDown size={14}/></button></div></div><div className="category-row">{categories.map(item=><button key={item} className={category===item?'selected':''} onClick={()=>setCategory(item)}>{item}<sup>{item==='Todo el setup'?products.length:products.filter(p=>p.category===item).length}</sup></button>)}<span className="result-count">Mostrando {shown.length} productos</span></div>{catalogError&&<div className="empty-state"><h3>Catálogo temporalmente no disponible</h3><p>{catalogError}</p><button className="button button-primary" onClick={loadProducts}>Volver a intentar</button></div>}<div className="product-grid">{shown.map(p=><ProductCard key={p.id} product={p} onAdd={add} admin={user?.role==='admin'} onEdit={editProduct} onDelete={deleteProduct} favorite={favorites.includes(p.id)} onFavorite={id=>setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>)}</div>{!catalogError&&shown.length===0&&<div className="empty-state"><Search/><h3>{query?'No encontramos ese equipo.':'El catálogo está actualizándose.'}</h3><p>{query?'Prueba con otro nombre o categoría.':'Vuelve en un momento para consultar disponibilidad.'}</p></div>}<p className="catalog-disclaimer">Precios de referencia consultados el 25 de septiembre de 2026 en los enlaces de cada producto. Pueden cambiar y no se sincronizan automáticamente con las tiendas. Las existencias indicadas corresponden al inventario de NEXUS.</p></section>
    <section className="feature-banner" id="featured"><div className="feature-image"><img src="https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1300&q=90" alt="Torre de PC gaming personalizada"/></div><div className="feature-copy"><p className="eyebrow">TU SETUP, TUS REGLAS</p><h2>NO SOLO JUEGUES.<br/><em>HAZ QUE CUENTE.</em></h2><p>Desde una primera build hasta el setup que llevas tiempo imaginando: elige tus piezas, conoce el precio y empieza a jugar.</p><a className="button button-light" href="#catalogo">Arma tu setup <ArrowRight size={16}/></a><div className="feature-number">N° 01 <span>PERFORMANCE SERIES</span></div></div></section>
    {user&&<section className="orders-section section-wrap" id="account"><div className="section-heading compact"><div><p className="eyebrow">TU CUENTA</p><h2>HOLA, <em>{user.name.split(' ')[0].toUpperCase()}.</em></h2></div>{user.role==='admin'&&<button className="button button-primary" onClick={()=>{setEditingProductId(null);setProductDraft({name:'',category:'PC armada',description:'',price_mxn:'',stock:'',image_url:'',source_url:''});setAdminForm(!adminForm);}}><Plus size={16}/> Nuevo producto</button>}</div>{adminForm&&user.role==='admin'&&<form className="admin-form" onSubmit={saveProduct}><h3>{editingProductId?'Editar producto':'Nuevo producto'}</h3><input placeholder="Nombre del producto" required value={productDraft.name} onChange={e=>setProductDraft({...productDraft,name:e.target.value})}/><select value={productDraft.category} onChange={e=>setProductDraft({...productDraft,category:e.target.value})}><option>PC armada</option><option>Monitores</option><option>Accesorios</option></select><input placeholder="Descripción y especificaciones" required value={productDraft.description} onChange={e=>setProductDraft({...productDraft,description:e.target.value})}/><input placeholder="Precio MXN" type="number" min="0" step="0.01" required value={productDraft.price_mxn} onChange={e=>setProductDraft({...productDraft,price_mxn:e.target.value})}/><input placeholder="Existencias propias" type="number" min="0" required value={productDraft.stock} onChange={e=>setProductDraft({...productDraft,stock:e.target.value})}/><input placeholder="URL de imagen" type="url" required value={productDraft.image_url} onChange={e=>setProductDraft({...productDraft,image_url:e.target.value})}/><input placeholder="Enlace de precio del proveedor (opcional)" type="url" value={productDraft.source_url} onChange={e=>setProductDraft({...productDraft,source_url:e.target.value})}/><button className="button button-primary">{editingProductId?'Guardar cambios':'Publicar producto'}</button>{editingProductId&&<button type="button" className="button button-light" onClick={()=>{setAdminForm(false);setEditingProductId(null);}}>Cancelar</button>}</form>}<OrderList orders={orders} user={user} onUpdate={updateOrder}/></section>}
    </main><footer className="footer"><a href="#top" className="brand"><span className="brand-icon"><Gamepad2 size={22}/></span><span>NEXUS<small>PC GAMING</small></span></a><p>Hecho para ir un nivel más allá.</p><div>© 2026 NEXUS · Precios de referencia sujetos a cambio</div></footer>
    {drawer&&<div className="scrim drawer-scrim" onMouseDown={e=>e.target===e.currentTarget&&setDrawer(false)}><aside className="cart-drawer"><div className="drawer-head"><div><p className="eyebrow">TU SELECCIÓN</p><h2>Carrito <span>({count})</span></h2></div><button className="icon-button" onClick={()=>setDrawer(false)}><X/></button></div>{cart.length?<><div className="cart-items">{cart.map(item=><div className="cart-item" key={item.id}><img src={item.image_url} alt=""/><div className="cart-item-main"><b>{item.name}</b><strong>{money(item.price_mxn)}</strong><div className="quantity"><button onClick={()=>adjust(item.id,-1)}><Minus size={13}/></button><span>{item.quantity}</span><button onClick={()=>adjust(item.id,1)}><Plus size={13}/></button></div></div><button className="remove-item" onClick={()=>adjust(item.id,-item.quantity)}><X size={15}/></button></div>)}</div><div className="cart-summary"><div><span>Subtotal de referencia</span><b>{money(total)}</b></div><small>El precio y la disponibilidad pueden variar; confirma con el proveedor antes de comprar.</small><button className="button button-primary wide" onClick={checkout}><span>Registrar pedido</span><ArrowRight size={16}/></button><p><ShieldCheck size={13}/> Se registra el pedido; el pago se acuerda fuera de esta plataforma.</p></div></>:<div className="cart-empty"><ShoppingCart size={40}/><h3>Tu setup comienza aquí.</h3><p>Agrega hardware desde el catálogo y aparecerá en esta lista.</p><button className="button button-primary" onClick={()=>setDrawer(false)}>Explorar catálogo</button></div>}</aside></div>}
    {modal&&<AuthModal onClose={()=>setModal(false)} onSuccess={authenticate} request={cart.length?'checkout':'account'}/>}<div className={`toast ${notice?'visible':''}`}><Check size={16}/>{notice}</div>
  </div>;
}
